version: "3.8"

services:
  backend:
    image: back-end
    container_name: fitness-backend
    ports:
      - "8080:8080"
    networks:
      - fitness-net

  frontend:
    image: front-end
    container_name: fitness-frontend
    ports:
      - "5173:5173"
    networks:
      - fitness-net
    depends_on:
      - backend

networks:
  fitness-net:
    driver: bridge
