version: "3.8"

services:
  backend:
    image: vooradiakshay741/fitness-store-backend
    container_name: fitness-backend
    ports:
      - "8080:8080"
    networks:
      - fitness-net

  frontend:
    image: vooradiakshay741/fitness-store-frontend
    container_name: fitness-frontend
    ports:
      - "5173:5173"
    networks:
      - fitness-net
    depends_on:
      - backend

networks:
  fitness-net:
    driver: bridge
