spring:
  application:
    name: backend
  data:
    mongodb:
      uri: mongodb+srv://akshay:akshay@cluster0.acasm.mongodb.net?retryWrites=true&w=majority&appName=Cluster0
      auto-index-creation: true
      database: fitness_store
