spring:
  application:
    name: backend
  data:
    mongodb:
      uri: mongodb+srv://vooradiakshay:akshay@cluster0.oer5yiw.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      auto-index-creation: true
      database: fitness_store
