spring:
  application:
    name: backend
  data:
    mongodb:
      uri: mongodb+srv://atiqshaik2409:tdnJIrbO7SrThFi9@ecomm.xenrzdk.mongodb.net/?retryWrites=true&w=majority&appName=ecomm
      auto-index-creation: true
      database: ecomm
